# Generated by Django 5.1.5 on 2025-03-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('?', 'Sin asignar'), ('M', 'Manos'), ('F', 'Full Set Francesas/Baby Boomer'), ('P', 'Pies'), ('R', 'Retiro')], default='M', max_length=2, null=True),
        ),
    ]
