# Generated by Django 5.1.5 on 2025-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicio_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='id_cliente',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='id_servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(related_name='citas', to='core.servicio'),
        ),
    ]
