# Generated by Django 5.1.5 on 2025-04-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_id_cliente_cita_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='comprobante',
            field=models.FileField(null=True, upload_to='documentos/'),
        ),
    ]
