# Generated by Django 5.1.5 on 2025-04-14 21:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cita_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechabloqueada',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='comprobante',
            field=models.FileField(null=True, upload_to='citas/comprobantes/'),
        ),
        migrations.CreateModel(
            name='HorasBloqueadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(19, 0), '7:00 PM')])),
                ('fecha_bloqueada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_bloqueadas', to='core.fechabloqueada')),
            ],
        ),
    ]
