# Generated by Django 5.1.5 on 2025-04-14 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fechabloqueada_motivo_alter_cita_comprobante_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HorasBloqueadas',
            new_name='HoraBloqueadas',
        ),
        migrations.AlterModelTable(
            name='horabloqueadas',
            table='horas_bloqueadas',
        ),
    ]
