# Generated by Django 5.1.5 on 2025-04-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_horabloqueadas_horabloqueada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechabloqueada',
            name='motivo',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
