# Generated by Django 5.1.5 on 2025-05-23 23:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_fechabloqueada_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(choices=[(datetime.time(9, 0), '9:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(19, 0), '7:00 PM')])),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_disponible', to='core.servicio')),
            ],
            options={
                'db_table': 'horarios_servicio',
            },
        ),
    ]
