# Generated by Django 5.1.5 on 2025-05-24 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_horarioservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='horarioservicio',
            name='servicio',
        ),
        migrations.AddField(
            model_name='horarioservicio',
            name='categoria',
            field=models.CharField(choices=[('?', 'Sin asignar'), ('M', 'Manos'), ('F', 'Full Set Francesas/Baby Boomer'), ('P', 'Pies'), ('R', 'Retiro')], default='?', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='horabloqueada',
            name='hora',
            field=models.TimeField(choices=[(None, 'Sin asignar'), (datetime.time(9, 0), '9:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(19, 0), '7:00 PM')]),
        ),
        migrations.AlterField(
            model_name='horarioservicio',
            name='hora',
            field=models.TimeField(choices=[(None, 'Sin asignar'), (datetime.time(9, 0), '9:00 AM'), (datetime.time(12, 0), '12:00 PM'), (datetime.time(16, 0), '4:00 PM'), (datetime.time(19, 0), '7:00 PM')]),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('?', 'Sin asignar'), ('M', 'Manos'), ('F', 'Full Set Francesas/Baby Boomer'), ('P', 'Pies'), ('R', 'Retiro')], default='?', max_length=2, null=True),
        ),
    ]
