# Generated by Django 5.1.5 on 2025-05-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_horario_remove_horarioservicio_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=2, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
