# Generated by Django 5.1.5 on 2025-05-24 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_categorias_servicio_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioservicio',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_disponibles', to='core.categorias'),
        ),
    ]
