# Generated by Django 5.1.5 on 2025-02-02 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2, null=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField(unique=True)),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.servicio')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.usuario')),
            ],
            options={
                'db_table': 'citas',
            },
        ),
    ]
