# Generated by Django 5.1.5 on 2025-02-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_usuario_fecha_creacion_alter_servicio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
